# Generated by Django 4.0.5 on 2022-07-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField(verbose_name='edad del propietario')),
                ('nacionalidad', models.CharField(choices=[('ecuatoriana', 'Ecuatoriana'), ('peruana', 'Peruana'), ('colombiana', 'Colombiana')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costoDepartamento', models.IntegerField(verbose_name='costo departamento')),
                ('numCuartos', models.IntegerField(verbose_name='numero de cuartos')),
                ('numBanios', models.IntegerField(verbose_name='numero de baños')),
                ('valorAlicuota', models.IntegerField(verbose_name='valor alicuota')),
                ('Propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='administrativo.propietario')),
            ],
        ),
    ]
